# Generated by Django 4.0.3 on 2022-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unreadCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
