# Generated by Django 4.0.3 on 2022-07-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_message_unreadcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
